language: php

# For javascript behat tests we need sudo
sudo: true
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.1
 - 7.2

addons:
 firefox: 47.0.1
 postgresql: 9.4
 apt:
   packages:
    - openjdk-8-jre-headless

env:
 global:
  - MOODLE_BRANCH=MOODLE_38_STABLE
  - IGNORE_NAMES=mobile_*.mustache # Mobile mustache has specific syntax, ignore their templates
 matrix:
  - DB=pgsql
  - DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 14.0
  - nvm use 14.0
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  # - moodle-plugin-ci phpcpd # subplugins often have similar code and cause "duplicated code" errors
  # - moodle-plugin-ci phpmd # too much noise from this check, maybe, some day...
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt -t stylelint:css -t js
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
